[workspace]
members = [
    "lib",
    "program",
    "script",
]
resolver = "2"

[workspace.dependencies]
alloy-sol-types = { version = "0.8.5", features = ["eip712-serde"] }
alloy-primitives = { version = "0.8.5", features = ["serde"] }
